### PR TITLE
Update paths for jss v10

### PR DESCRIPTION
**Pull request by HenriBeck**

### CODE REVIEW

**Comment by kof** [comment]
have you tried running it locally? does it all work?

**Comment by HenriBeck** [comment]
No, not yet. Will test it this evening or tomorrow evening

**Comment by HenriBeck** [comment]
It works now, though we will have to limit the version to v10 and above.

**Comment by kof** [comment]
What happens if you run it locally and select v9 and lower?

**Comment by HenriBeck** [comment]
I get 404 for the plugins etc. The pages which were also before in the main repo are fine.

**Review by kof — APPROVED** [review]
lets evtl add something that redirects to old.cssinjs.org when selecting an older version than v10 or when user comes from a URL with http://cssinjs.org/?v=v9.8.7 or lower

**Pull request closed without merging**
