### PR TITLE
Fix scrollTo issue on page load

### PR DESCRIPTION
**Pull request by typical000**

### CODE REVIEW

**Comment by kof** [comment]
tried, your fix, still doesn't work for me locally

**Comment by kof** [comment]
I am on mac/latest chrome, trying this url http://127.0.0.1:8080/json-api/?v=v6.4.0#font-face

**Comment by typical000** [comment]
0_o so quickly... and strange. Have you launched `npm run all:prod` ?
I'm looking on win, latest chrome, the same url (json-api/?v=v6.4.0#font-face)

**Comment by kof** [comment]
yes, sure, ensured cache isn't used as well, thats strange

**Comment by typical000** [comment]
Really strange - updated FF to latest version and it works too. I can try on ubuntu tomorrow... But I think that's not an OS or browser issue -_-.

**Comment by kof** [comment]
just did all:prod and it worked

**Comment by kof** [comment]
dunno what has changed, strange, the only diff is the build-html

**Comment by typical000** [comment]
I thing the main problem was just versions that we add to bundle names

**Pull request merged**
